/**
 * Convolutional Autoencoder
 * WebUI to build, train and tune a Convolutional Autoencoder
 *
 * OpenAPI spec version: 1.1.7
 * Contact: leon.schuetz@student.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Image'));
  } else {
    // Browser globals (root is window)
    if (!root.ConvolutionalAutoencoder) {
      root.ConvolutionalAutoencoder = {};
    }
    root.ConvolutionalAutoencoder.ImageData = factory(root.ConvolutionalAutoencoder.ApiClient, root.ConvolutionalAutoencoder.Image);
  }
}(this, function(ApiClient, Image) {
  'use strict';




  /**
   * The ImageData model module.
   * @module model/ImageData
   * @version 1.1.7
   */

  /**
   * Constructs a new <code>ImageData</code>.
   * @alias module:model/ImageData
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ImageData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageData} obj Optional instance to populate.
   * @return {module:model/ImageData} The populated <code>ImageData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('numImages')) {
        obj['numImages'] = ApiClient.convertToType(data['numImages'], 'Number');
      }
      if (data.hasOwnProperty('resX')) {
        obj['resX'] = ApiClient.convertToType(data['resX'], 'Number');
      }
      if (data.hasOwnProperty('resY')) {
        obj['resY'] = ApiClient.convertToType(data['resY'], 'Number');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], [Image]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} numImages
   */
  exports.prototype['numImages'] = undefined;
  /**
   * @member {Number} resX
   */
  exports.prototype['resX'] = undefined;
  /**
   * @member {Number} resY
   */
  exports.prototype['resY'] = undefined;
  /**
   * @member {Array.<module:model/Image>} images
   */
  exports.prototype['images'] = undefined;



  return exports;
}));


