/**
 * Convolutional Autoencoder
 * WebUI to build, train and tune a Convolutional Autoencoder
 *
 * OpenAPI spec version: 1.2.2
 * Contact: leon.schuetz@student.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ConvolutionalAutoencoder) {
      root.ConvolutionalAutoencoder = {};
    }
    root.ConvolutionalAutoencoder.LearningRate = factory(root.ConvolutionalAutoencoder.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LearningRate model module.
   * @module model/LearningRate
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>LearningRate</code>.
   * @alias module:model/LearningRate
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>LearningRate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningRate} obj Optional instance to populate.
   * @return {module:model/LearningRate} The populated <code>LearningRate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('learning_rate_function')) {
        obj['learning_rate_function'] = ApiClient.convertToType(data['learning_rate_function'], 'String');
      }
      if (data.hasOwnProperty('lr_initial_learning_rate')) {
        obj['lr_initial_learning_rate'] = ApiClient.convertToType(data['lr_initial_learning_rate'], ['Number']);
      }
      if (data.hasOwnProperty('lr_decay_steps')) {
        obj['lr_decay_steps'] = ApiClient.convertToType(data['lr_decay_steps'], ['Number']);
      }
      if (data.hasOwnProperty('lr_decay_rate')) {
        obj['lr_decay_rate'] = ApiClient.convertToType(data['lr_decay_rate'], ['Number']);
      }
      if (data.hasOwnProperty('lr_staircase')) {
        obj['lr_staircase'] = ApiClient.convertToType(data['lr_staircase'], ['Boolean']);
      }
      if (data.hasOwnProperty('lr_boundaries')) {
        obj['lr_boundaries'] = ApiClient.convertToType(data['lr_boundaries'], [['Number']]);
      }
      if (data.hasOwnProperty('lr_values')) {
        obj['lr_values'] = ApiClient.convertToType(data['lr_values'], [['Number']]);
      }
      if (data.hasOwnProperty('lr_end_learning_rate')) {
        obj['lr_end_learning_rate'] = ApiClient.convertToType(data['lr_end_learning_rate'], ['Number']);
      }
      if (data.hasOwnProperty('lr_power')) {
        obj['lr_power'] = ApiClient.convertToType(data['lr_power'], ['Number']);
      }
      if (data.hasOwnProperty('lr_cycle')) {
        obj['lr_cycle'] = ApiClient.convertToType(data['lr_cycle'], ['Boolean']);
      }
    }
    return obj;
  }

  /**
   * @member {String} learning_rate_function
   * @default 'static'
   */
  exports.prototype['learning_rate_function'] = 'static';
  /**
   * @member {Array.<Number>} lr_initial_learning_rate
   */
  exports.prototype['lr_initial_learning_rate'] = undefined;
  /**
   * @member {Array.<Number>} lr_decay_steps
   */
  exports.prototype['lr_decay_steps'] = undefined;
  /**
   * @member {Array.<Number>} lr_decay_rate
   */
  exports.prototype['lr_decay_rate'] = undefined;
  /**
   * @member {Array.<Boolean>} lr_staircase
   */
  exports.prototype['lr_staircase'] = undefined;
  /**
   * @member {Array.<Array.<Number>>} lr_boundaries
   */
  exports.prototype['lr_boundaries'] = undefined;
  /**
   * @member {Array.<Array.<Number>>} lr_values
   */
  exports.prototype['lr_values'] = undefined;
  /**
   * @member {Array.<Number>} lr_end_learning_rate
   */
  exports.prototype['lr_end_learning_rate'] = undefined;
  /**
   * @member {Array.<Number>} lr_power
   */
  exports.prototype['lr_power'] = undefined;
  /**
   * @member {Array.<Boolean>} lr_cycle
   */
  exports.prototype['lr_cycle'] = undefined;



  return exports;
}));


