/**
 * Convolutional Autoencoder
 * WebUI to build, train and tune a Convolutional Autoencoder
 *
 * OpenAPI spec version: 1.2.0
 * Contact: leon.schuetz@student.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Image'));
  } else {
    // Browser globals (root is window)
    if (!root.ConvolutionalAutoencoder) {
      root.ConvolutionalAutoencoder = {};
    }
    root.ConvolutionalAutoencoder.ProcessedImageData = factory(root.ConvolutionalAutoencoder.ApiClient, root.ConvolutionalAutoencoder.Image);
  }
}(this, function(ApiClient, Image) {
  'use strict';




  /**
   * The ProcessedImageData model module.
   * @module model/ProcessedImageData
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>ProcessedImageData</code>.
   * @alias module:model/ProcessedImageData
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ProcessedImageData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessedImageData} obj Optional instance to populate.
   * @return {module:model/ProcessedImageData} The populated <code>ProcessedImageData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

        if (data.hasOwnProperty('epoch')) {
            obj['epoch'] = ApiClient.convertToType(data['epoch'], 'Number');
        }
        if (data.hasOwnProperty('step')) {
            obj['step'] = ApiClient.convertToType(data['step'], 'Number');
        }
      if (data.hasOwnProperty('inputLayer')) {
        obj['inputLayer'] = ApiClient.convertToType(data['inputLayer'], [Image]);
      }
      if (data.hasOwnProperty('latentLayer')) {
          obj['latentLayer'] = ApiClient.convertToType(data['latentLayer'], [[Image]]);
      }
      if (data.hasOwnProperty('outputLayer')) {
        obj['outputLayer'] = ApiClient.convertToType(data['outputLayer'], [Image]);
      }
    }
    return obj;
  }

    /**
     * @member {Number} epoch
     */
    exports.prototype['epoch'] = undefined;
    /**
     * @member {Number} step
     */
    exports.prototype['step'] = undefined;
  /**
   * @member {Array.<module:model/Image>} inputLayer
   */
  exports.prototype['inputLayer'] = undefined;
  /**
   * @member {Array.<Array.<module:model/Image>>} latentLayer
   */
  exports.prototype['latentLayer'] = undefined;
  /**
   * @member {Array.<module:model/Image>} outputLayer
   */
  exports.prototype['outputLayer'] = undefined;



  return exports;
}));


