/**
 * Convolutional Autoencoder
 * WebUI to build, train and tune a Convolutional Autoencoder
 *
 * OpenAPI spec version: 1.2.2
 * Contact: leon.schuetz@student.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ConvolutionalAutoencoder) {
      root.ConvolutionalAutoencoder = {};
    }
    root.ConvolutionalAutoencoder.TrainPerformanceDataPoint = factory(root.ConvolutionalAutoencoder.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TrainPerformanceDataPoint model module.
   * @module model/TrainPerformanceDataPoint
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>TrainPerformanceDataPoint</code>.
   * @alias module:model/TrainPerformanceDataPoint
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>TrainPerformanceDataPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainPerformanceDataPoint} obj Optional instance to populate.
   * @return {module:model/TrainPerformanceDataPoint} The populated <code>TrainPerformanceDataPoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('epoch')) {
        obj['epoch'] = ApiClient.convertToType(data['epoch'], 'Number');
      }
      if (data.hasOwnProperty('step')) {
        obj['step'] = ApiClient.convertToType(data['step'], 'Number');
      }
      if (data.hasOwnProperty('cost')) {
        obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
      }
      if (data.hasOwnProperty('currentLearningRate')) {
        obj['currentLearningRate'] = ApiClient.convertToType(data['currentLearningRate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} epoch
   */
  exports.prototype['epoch'] = undefined;
  /**
   * @member {Number} step
   */
  exports.prototype['step'] = undefined;
  /**
   * @member {Number} cost
   */
  exports.prototype['cost'] = undefined;
  /**
   * @member {Number} currentLearningRate
   */
  exports.prototype['currentLearningRate'] = undefined;



  return exports;
}));


