/**
 * Convolutional Autoencoder
 * WebUI to build, train and tune a Convolutional Autoencoder
 *
 * OpenAPI spec version: 1.1.7
 * Contact: leon.schuetz@student.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
      define(['ApiClient', 'model/TrainPerformanceDataPoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
      module.exports = factory(require('../ApiClient'), require('./TrainPerformanceDataPoint'));
  } else {
    // Browser globals (root is window)
    if (!root.ConvolutionalAutoencoder) {
      root.ConvolutionalAutoencoder = {};
    }
      root.ConvolutionalAutoencoder.TrainPerformance = factory(root.ConvolutionalAutoencoder.ApiClient, root.ConvolutionalAutoencoder.TrainPerformanceDataPoint);
  }
}(this, function (ApiClient, TrainPerformanceDataPoint) {
  'use strict';




  /**
   * The TrainPerformance model module.
   * @module model/TrainPerformance
   * @version 1.1.7
   */

  /**
   * Constructs a new <code>TrainPerformance</code>.
   * @alias module:model/TrainPerformance
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TrainPerformance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainPerformance} obj Optional instance to populate.
   * @return {module:model/TrainPerformance} The populated <code>TrainPerformance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('model_id')) {
        obj['model_id'] = ApiClient.convertToType(data['model_id'], 'String');
      }
        if (data.hasOwnProperty('train_status')) {
            obj['train_status'] = ApiClient.convertToType(data['train_status'], 'String');
      }
        if (data.hasOwnProperty('train_performance_data')) {
            obj['train_performance_data'] = ApiClient.convertToType(data['train_performance_data'], [TrainPerformanceDataPoint]);
      }
    }
    return obj;
  }

  /**
   * @member {String} model_id
   */
  exports.prototype['model_id'] = undefined;
  /**
   * @member {String} train_status
   */
  exports.prototype['train_status'] = undefined;
    /**
     * @member {Array.<module:model/TrainPerformanceDataPoint>} train_performance_data
   */
    exports.prototype['train_performance_data'] = undefined;



  return exports;
}));


