# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ParameterLists(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, input_shape_list: List[List[int]]=None, number_of_stacks_list: List[List[int]]=None, filter_size_list: List[List[int]]=None, mirror_weight_list: List[bool]=None, activation_function_list: List[str]=None, batch_size_list: List[int]=None, n_epoch_list: List[int]=None, use_tensorboard: bool=None, verbose: bool=None, learning_rate_function_list: List[str]=None, lr_initial_learning_rate_list: List[float]=None, lr_decay_step_list: List[int]=None, lr_decay_rate_list: List[float]=None, lr_staircase_list: List[bool]=None, lr_boundary_list: List[List[int]]=None, lr_value_list: List[List[float]]=None, lr_end_learning_rate_list: List[float]=None, lr_power_list: List[float]=None, lr_cycle_list: List[bool]=None, opimizer_list: List[str]=None, momentum_list: List[float]=None, random_function_for_weights_list: List[str]=None, rw_alpha_list: List[float]=None, rw_beta_list: List[float]=None, rw_mean_list: List[float]=None, rw_stddev_list: List[float]=None, rw_lam_list: List[float]=None, rw_minval_list: List[float]=None, rw_maxval_list: List[float]=None, rw_seed_list: List[int]=None, random_function_for_biases_list: List[str]=None, rb_alpha_list: List[float]=None, rb_beta_list: List[float]=None, rb_mean_list: List[float]=None, rb_stddev_list: List[float]=None, rb_lam_list: List[float]=None, rb_minval_list: List[float]=None, rb_maxval_list: List[float]=None, rb_seed_list: List[int]=None, session_saver_path: str=None, load_prev_session: bool=None):
        """
        ParameterLists - a model defined in Swagger

        :param input_shape_list: The input_shape_list of this ParameterLists.
        :type input_shape_list: List[List[int]]
        :param number_of_stacks_list: The number_of_stacks_list of this ParameterLists.
        :type number_of_stacks_list: List[List[int]]
        :param filter_size_list: The filter_size_list of this ParameterLists.
        :type filter_size_list: List[List[int]]
        :param mirror_weight_list: The mirror_weight_list of this ParameterLists.
        :type mirror_weight_list: List[bool]
        :param activation_function_list: The activation_function_list of this ParameterLists.
        :type activation_function_list: List[str]
        :param batch_size_list: The batch_size_list of this ParameterLists.
        :type batch_size_list: List[int]
        :param n_epoch_list: The n_epoch_list of this ParameterLists.
        :type n_epoch_list: List[int]
        :param use_tensorboard: The use_tensorboard of this ParameterLists.
        :type use_tensorboard: bool
        :param verbose: The verbose of this ParameterLists.
        :type verbose: bool
        :param learning_rate_function_list: The learning_rate_function_list of this ParameterLists.
        :type learning_rate_function_list: List[str]
        :param lr_initial_learning_rate_list: The lr_initial_learning_rate_list of this ParameterLists.
        :type lr_initial_learning_rate_list: List[float]
        :param lr_decay_step_list: The lr_decay_step_list of this ParameterLists.
        :type lr_decay_step_list: List[int]
        :param lr_decay_rate_list: The lr_decay_rate_list of this ParameterLists.
        :type lr_decay_rate_list: List[float]
        :param lr_staircase_list: The lr_staircase_list of this ParameterLists.
        :type lr_staircase_list: List[bool]
        :param lr_boundary_list: The lr_boundary_list of this ParameterLists.
        :type lr_boundary_list: List[List[int]]
        :param lr_value_list: The lr_value_list of this ParameterLists.
        :type lr_value_list: List[List[float]]
        :param lr_end_learning_rate_list: The lr_end_learning_rate_list of this ParameterLists.
        :type lr_end_learning_rate_list: List[float]
        :param lr_power_list: The lr_power_list of this ParameterLists.
        :type lr_power_list: List[float]
        :param lr_cycle_list: The lr_cycle_list of this ParameterLists.
        :type lr_cycle_list: List[bool]
        :param opimizer_list: The opimizer_list of this ParameterLists.
        :type opimizer_list: List[str]
        :param momentum_list: The momentum_list of this ParameterLists.
        :type momentum_list: List[float]
        :param random_function_for_weights_list: The random_function_for_weights_list of this ParameterLists.
        :type random_function_for_weights_list: List[str]
        :param rw_alpha_list: The rw_alpha_list of this ParameterLists.
        :type rw_alpha_list: List[float]
        :param rw_beta_list: The rw_beta_list of this ParameterLists.
        :type rw_beta_list: List[float]
        :param rw_mean_list: The rw_mean_list of this ParameterLists.
        :type rw_mean_list: List[float]
        :param rw_stddev_list: The rw_stddev_list of this ParameterLists.
        :type rw_stddev_list: List[float]
        :param rw_lam_list: The rw_lam_list of this ParameterLists.
        :type rw_lam_list: List[float]
        :param rw_minval_list: The rw_minval_list of this ParameterLists.
        :type rw_minval_list: List[float]
        :param rw_maxval_list: The rw_maxval_list of this ParameterLists.
        :type rw_maxval_list: List[float]
        :param rw_seed_list: The rw_seed_list of this ParameterLists.
        :type rw_seed_list: List[int]
        :param random_function_for_biases_list: The random_function_for_biases_list of this ParameterLists.
        :type random_function_for_biases_list: List[str]
        :param rb_alpha_list: The rb_alpha_list of this ParameterLists.
        :type rb_alpha_list: List[float]
        :param rb_beta_list: The rb_beta_list of this ParameterLists.
        :type rb_beta_list: List[float]
        :param rb_mean_list: The rb_mean_list of this ParameterLists.
        :type rb_mean_list: List[float]
        :param rb_stddev_list: The rb_stddev_list of this ParameterLists.
        :type rb_stddev_list: List[float]
        :param rb_lam_list: The rb_lam_list of this ParameterLists.
        :type rb_lam_list: List[float]
        :param rb_minval_list: The rb_minval_list of this ParameterLists.
        :type rb_minval_list: List[float]
        :param rb_maxval_list: The rb_maxval_list of this ParameterLists.
        :type rb_maxval_list: List[float]
        :param rb_seed_list: The rb_seed_list of this ParameterLists.
        :type rb_seed_list: List[int]
        :param session_saver_path: The session_saver_path of this ParameterLists.
        :type session_saver_path: str
        :param load_prev_session: The load_prev_session of this ParameterLists.
        :type load_prev_session: bool
        """
        self.swagger_types = {
            'input_shape_list': List[List[int]],
            'number_of_stacks_list': List[List[int]],
            'filter_size_list': List[List[int]],
            'mirror_weight_list': List[bool],
            'activation_function_list': List[str],
            'batch_size_list': List[int],
            'n_epoch_list': List[int],
            'use_tensorboard': bool,
            'verbose': bool,
            'learning_rate_function_list': List[str],
            'lr_initial_learning_rate_list': List[float],
            'lr_decay_step_list': List[int],
            'lr_decay_rate_list': List[float],
            'lr_staircase_list': List[bool],
            'lr_boundary_list': List[List[int]],
            'lr_value_list': List[List[float]],
            'lr_end_learning_rate_list': List[float],
            'lr_power_list': List[float],
            'lr_cycle_list': List[bool],
            'opimizer_list': List[str],
            'momentum_list': List[float],
            'random_function_for_weights_list': List[str],
            'rw_alpha_list': List[float],
            'rw_beta_list': List[float],
            'rw_mean_list': List[float],
            'rw_stddev_list': List[float],
            'rw_lam_list': List[float],
            'rw_minval_list': List[float],
            'rw_maxval_list': List[float],
            'rw_seed_list': List[int],
            'random_function_for_biases_list': List[str],
            'rb_alpha_list': List[float],
            'rb_beta_list': List[float],
            'rb_mean_list': List[float],
            'rb_stddev_list': List[float],
            'rb_lam_list': List[float],
            'rb_minval_list': List[float],
            'rb_maxval_list': List[float],
            'rb_seed_list': List[int],
            'session_saver_path': str,
            'load_prev_session': bool
        }

        self.attribute_map = {
            'input_shape_list': 'inputShapeList',
            'number_of_stacks_list': 'numberOfStacksList',
            'filter_size_list': 'filterSizeList',
            'mirror_weight_list': 'mirrorWeightList',
            'activation_function_list': 'activationFunctionList',
            'batch_size_list': 'batchSizeList',
            'n_epoch_list': 'nEpochList',
            'use_tensorboard': 'useTensorboard',
            'verbose': 'verbose',
            'learning_rate_function_list': 'learningRateFunctionList',
            'lr_initial_learning_rate_list': 'lrInitialLearningRateList',
            'lr_decay_step_list': 'lrDecayStepList',
            'lr_decay_rate_list': 'lrDecayRateList',
            'lr_staircase_list': 'lrStaircaseList',
            'lr_boundary_list': 'lrBoundaryList',
            'lr_value_list': 'lrValueList',
            'lr_end_learning_rate_list': 'lrEndLearningRateList',
            'lr_power_list': 'lrPowerList',
            'lr_cycle_list': 'lrCycleList',
            'opimizer_list': 'opimizerList',
            'momentum_list': 'momentumList',
            'random_function_for_weights_list': 'randomFunctionForWeightsList',
            'rw_alpha_list': 'rwAlphaList',
            'rw_beta_list': 'rwBetaList',
            'rw_mean_list': 'rwMeanList',
            'rw_stddev_list': 'rwStddevList',
            'rw_lam_list': 'rwLamList',
            'rw_minval_list': 'rwMinvalList',
            'rw_maxval_list': 'rwMaxvalList',
            'rw_seed_list': 'rwSeedList',
            'random_function_for_biases_list': 'randomFunctionForBiasesList',
            'rb_alpha_list': 'rbAlphaList',
            'rb_beta_list': 'rbBetaList',
            'rb_mean_list': 'rbMeanList',
            'rb_stddev_list': 'rbStddevList',
            'rb_lam_list': 'rbLamList',
            'rb_minval_list': 'rbMinvalList',
            'rb_maxval_list': 'rbMaxvalList',
            'rb_seed_list': 'rbSeedList',
            'session_saver_path': 'sessionSaverPath',
            'load_prev_session': 'loadPrevSession'
        }

        self._input_shape_list = input_shape_list
        self._number_of_stacks_list = number_of_stacks_list
        self._filter_size_list = filter_size_list
        self._mirror_weight_list = mirror_weight_list
        self._activation_function_list = activation_function_list
        self._batch_size_list = batch_size_list
        self._n_epoch_list = n_epoch_list
        self._use_tensorboard = use_tensorboard
        self._verbose = verbose
        self._learning_rate_function_list = learning_rate_function_list
        self._lr_initial_learning_rate_list = lr_initial_learning_rate_list
        self._lr_decay_step_list = lr_decay_step_list
        self._lr_decay_rate_list = lr_decay_rate_list
        self._lr_staircase_list = lr_staircase_list
        self._lr_boundary_list = lr_boundary_list
        self._lr_value_list = lr_value_list
        self._lr_end_learning_rate_list = lr_end_learning_rate_list
        self._lr_power_list = lr_power_list
        self._lr_cycle_list = lr_cycle_list
        self._opimizer_list = opimizer_list
        self._momentum_list = momentum_list
        self._random_function_for_weights_list = random_function_for_weights_list
        self._rw_alpha_list = rw_alpha_list
        self._rw_beta_list = rw_beta_list
        self._rw_mean_list = rw_mean_list
        self._rw_stddev_list = rw_stddev_list
        self._rw_lam_list = rw_lam_list
        self._rw_minval_list = rw_minval_list
        self._rw_maxval_list = rw_maxval_list
        self._rw_seed_list = rw_seed_list
        self._random_function_for_biases_list = random_function_for_biases_list
        self._rb_alpha_list = rb_alpha_list
        self._rb_beta_list = rb_beta_list
        self._rb_mean_list = rb_mean_list
        self._rb_stddev_list = rb_stddev_list
        self._rb_lam_list = rb_lam_list
        self._rb_minval_list = rb_minval_list
        self._rb_maxval_list = rb_maxval_list
        self._rb_seed_list = rb_seed_list
        self._session_saver_path = session_saver_path
        self._load_prev_session = load_prev_session

    @classmethod
    def from_dict(cls, dikt) -> 'ParameterLists':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParameterLists of this ParameterLists.
        :rtype: ParameterLists
        """
        return deserialize_model(dikt, cls)

    @property
    def input_shape_list(self) -> List[List[int]]:
        """
        Gets the input_shape_list of this ParameterLists.

        :return: The input_shape_list of this ParameterLists.
        :rtype: List[List[int]]
        """
        return self._input_shape_list

    @input_shape_list.setter
    def input_shape_list(self, input_shape_list: List[List[int]]):
        """
        Sets the input_shape_list of this ParameterLists.

        :param input_shape_list: The input_shape_list of this ParameterLists.
        :type input_shape_list: List[List[int]]
        """

        self._input_shape_list = input_shape_list

    @property
    def number_of_stacks_list(self) -> List[List[int]]:
        """
        Gets the number_of_stacks_list of this ParameterLists.

        :return: The number_of_stacks_list of this ParameterLists.
        :rtype: List[List[int]]
        """
        return self._number_of_stacks_list

    @number_of_stacks_list.setter
    def number_of_stacks_list(self, number_of_stacks_list: List[List[int]]):
        """
        Sets the number_of_stacks_list of this ParameterLists.

        :param number_of_stacks_list: The number_of_stacks_list of this ParameterLists.
        :type number_of_stacks_list: List[List[int]]
        """

        self._number_of_stacks_list = number_of_stacks_list

    @property
    def filter_size_list(self) -> List[List[int]]:
        """
        Gets the filter_size_list of this ParameterLists.

        :return: The filter_size_list of this ParameterLists.
        :rtype: List[List[int]]
        """
        return self._filter_size_list

    @filter_size_list.setter
    def filter_size_list(self, filter_size_list: List[List[int]]):
        """
        Sets the filter_size_list of this ParameterLists.

        :param filter_size_list: The filter_size_list of this ParameterLists.
        :type filter_size_list: List[List[int]]
        """

        self._filter_size_list = filter_size_list

    @property
    def mirror_weight_list(self) -> List[bool]:
        """
        Gets the mirror_weight_list of this ParameterLists.

        :return: The mirror_weight_list of this ParameterLists.
        :rtype: List[bool]
        """
        return self._mirror_weight_list

    @mirror_weight_list.setter
    def mirror_weight_list(self, mirror_weight_list: List[bool]):
        """
        Sets the mirror_weight_list of this ParameterLists.

        :param mirror_weight_list: The mirror_weight_list of this ParameterLists.
        :type mirror_weight_list: List[bool]
        """

        self._mirror_weight_list = mirror_weight_list

    @property
    def activation_function_list(self) -> List[str]:
        """
        Gets the activation_function_list of this ParameterLists.

        :return: The activation_function_list of this ParameterLists.
        :rtype: List[str]
        """
        return self._activation_function_list

    @activation_function_list.setter
    def activation_function_list(self, activation_function_list: List[str]):
        """
        Sets the activation_function_list of this ParameterLists.

        :param activation_function_list: The activation_function_list of this ParameterLists.
        :type activation_function_list: List[str]
        """

        self._activation_function_list = activation_function_list

    @property
    def batch_size_list(self) -> List[int]:
        """
        Gets the batch_size_list of this ParameterLists.

        :return: The batch_size_list of this ParameterLists.
        :rtype: List[int]
        """
        return self._batch_size_list

    @batch_size_list.setter
    def batch_size_list(self, batch_size_list: List[int]):
        """
        Sets the batch_size_list of this ParameterLists.

        :param batch_size_list: The batch_size_list of this ParameterLists.
        :type batch_size_list: List[int]
        """

        self._batch_size_list = batch_size_list

    @property
    def n_epoch_list(self) -> List[int]:
        """
        Gets the n_epoch_list of this ParameterLists.

        :return: The n_epoch_list of this ParameterLists.
        :rtype: List[int]
        """
        return self._n_epoch_list

    @n_epoch_list.setter
    def n_epoch_list(self, n_epoch_list: List[int]):
        """
        Sets the n_epoch_list of this ParameterLists.

        :param n_epoch_list: The n_epoch_list of this ParameterLists.
        :type n_epoch_list: List[int]
        """

        self._n_epoch_list = n_epoch_list

    @property
    def use_tensorboard(self) -> bool:
        """
        Gets the use_tensorboard of this ParameterLists.

        :return: The use_tensorboard of this ParameterLists.
        :rtype: bool
        """
        return self._use_tensorboard

    @use_tensorboard.setter
    def use_tensorboard(self, use_tensorboard: bool):
        """
        Sets the use_tensorboard of this ParameterLists.

        :param use_tensorboard: The use_tensorboard of this ParameterLists.
        :type use_tensorboard: bool
        """

        self._use_tensorboard = use_tensorboard

    @property
    def verbose(self) -> bool:
        """
        Gets the verbose of this ParameterLists.

        :return: The verbose of this ParameterLists.
        :rtype: bool
        """
        return self._verbose

    @verbose.setter
    def verbose(self, verbose: bool):
        """
        Sets the verbose of this ParameterLists.

        :param verbose: The verbose of this ParameterLists.
        :type verbose: bool
        """

        self._verbose = verbose

    @property
    def learning_rate_function_list(self) -> List[str]:
        """
        Gets the learning_rate_function_list of this ParameterLists.

        :return: The learning_rate_function_list of this ParameterLists.
        :rtype: List[str]
        """
        return self._learning_rate_function_list

    @learning_rate_function_list.setter
    def learning_rate_function_list(self, learning_rate_function_list: List[str]):
        """
        Sets the learning_rate_function_list of this ParameterLists.

        :param learning_rate_function_list: The learning_rate_function_list of this ParameterLists.
        :type learning_rate_function_list: List[str]
        """

        self._learning_rate_function_list = learning_rate_function_list

    @property
    def lr_initial_learning_rate_list(self) -> List[float]:
        """
        Gets the lr_initial_learning_rate_list of this ParameterLists.

        :return: The lr_initial_learning_rate_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._lr_initial_learning_rate_list

    @lr_initial_learning_rate_list.setter
    def lr_initial_learning_rate_list(self, lr_initial_learning_rate_list: List[float]):
        """
        Sets the lr_initial_learning_rate_list of this ParameterLists.

        :param lr_initial_learning_rate_list: The lr_initial_learning_rate_list of this ParameterLists.
        :type lr_initial_learning_rate_list: List[float]
        """

        self._lr_initial_learning_rate_list = lr_initial_learning_rate_list

    @property
    def lr_decay_step_list(self) -> List[int]:
        """
        Gets the lr_decay_step_list of this ParameterLists.

        :return: The lr_decay_step_list of this ParameterLists.
        :rtype: List[int]
        """
        return self._lr_decay_step_list

    @lr_decay_step_list.setter
    def lr_decay_step_list(self, lr_decay_step_list: List[int]):
        """
        Sets the lr_decay_step_list of this ParameterLists.

        :param lr_decay_step_list: The lr_decay_step_list of this ParameterLists.
        :type lr_decay_step_list: List[int]
        """

        self._lr_decay_step_list = lr_decay_step_list

    @property
    def lr_decay_rate_list(self) -> List[float]:
        """
        Gets the lr_decay_rate_list of this ParameterLists.

        :return: The lr_decay_rate_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._lr_decay_rate_list

    @lr_decay_rate_list.setter
    def lr_decay_rate_list(self, lr_decay_rate_list: List[float]):
        """
        Sets the lr_decay_rate_list of this ParameterLists.

        :param lr_decay_rate_list: The lr_decay_rate_list of this ParameterLists.
        :type lr_decay_rate_list: List[float]
        """

        self._lr_decay_rate_list = lr_decay_rate_list

    @property
    def lr_staircase_list(self) -> List[bool]:
        """
        Gets the lr_staircase_list of this ParameterLists.

        :return: The lr_staircase_list of this ParameterLists.
        :rtype: List[bool]
        """
        return self._lr_staircase_list

    @lr_staircase_list.setter
    def lr_staircase_list(self, lr_staircase_list: List[bool]):
        """
        Sets the lr_staircase_list of this ParameterLists.

        :param lr_staircase_list: The lr_staircase_list of this ParameterLists.
        :type lr_staircase_list: List[bool]
        """

        self._lr_staircase_list = lr_staircase_list

    @property
    def lr_boundary_list(self) -> List[List[int]]:
        """
        Gets the lr_boundary_list of this ParameterLists.

        :return: The lr_boundary_list of this ParameterLists.
        :rtype: List[List[int]]
        """
        return self._lr_boundary_list

    @lr_boundary_list.setter
    def lr_boundary_list(self, lr_boundary_list: List[List[int]]):
        """
        Sets the lr_boundary_list of this ParameterLists.

        :param lr_boundary_list: The lr_boundary_list of this ParameterLists.
        :type lr_boundary_list: List[List[int]]
        """

        self._lr_boundary_list = lr_boundary_list

    @property
    def lr_value_list(self) -> List[List[float]]:
        """
        Gets the lr_value_list of this ParameterLists.

        :return: The lr_value_list of this ParameterLists.
        :rtype: List[List[float]]
        """
        return self._lr_value_list

    @lr_value_list.setter
    def lr_value_list(self, lr_value_list: List[List[float]]):
        """
        Sets the lr_value_list of this ParameterLists.

        :param lr_value_list: The lr_value_list of this ParameterLists.
        :type lr_value_list: List[List[float]]
        """

        self._lr_value_list = lr_value_list

    @property
    def lr_end_learning_rate_list(self) -> List[float]:
        """
        Gets the lr_end_learning_rate_list of this ParameterLists.

        :return: The lr_end_learning_rate_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._lr_end_learning_rate_list

    @lr_end_learning_rate_list.setter
    def lr_end_learning_rate_list(self, lr_end_learning_rate_list: List[float]):
        """
        Sets the lr_end_learning_rate_list of this ParameterLists.

        :param lr_end_learning_rate_list: The lr_end_learning_rate_list of this ParameterLists.
        :type lr_end_learning_rate_list: List[float]
        """

        self._lr_end_learning_rate_list = lr_end_learning_rate_list

    @property
    def lr_power_list(self) -> List[float]:
        """
        Gets the lr_power_list of this ParameterLists.

        :return: The lr_power_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._lr_power_list

    @lr_power_list.setter
    def lr_power_list(self, lr_power_list: List[float]):
        """
        Sets the lr_power_list of this ParameterLists.

        :param lr_power_list: The lr_power_list of this ParameterLists.
        :type lr_power_list: List[float]
        """

        self._lr_power_list = lr_power_list

    @property
    def lr_cycle_list(self) -> List[bool]:
        """
        Gets the lr_cycle_list of this ParameterLists.

        :return: The lr_cycle_list of this ParameterLists.
        :rtype: List[bool]
        """
        return self._lr_cycle_list

    @lr_cycle_list.setter
    def lr_cycle_list(self, lr_cycle_list: List[bool]):
        """
        Sets the lr_cycle_list of this ParameterLists.

        :param lr_cycle_list: The lr_cycle_list of this ParameterLists.
        :type lr_cycle_list: List[bool]
        """

        self._lr_cycle_list = lr_cycle_list

    @property
    def opimizer_list(self) -> List[str]:
        """
        Gets the opimizer_list of this ParameterLists.

        :return: The opimizer_list of this ParameterLists.
        :rtype: List[str]
        """
        return self._opimizer_list

    @opimizer_list.setter
    def opimizer_list(self, opimizer_list: List[str]):
        """
        Sets the opimizer_list of this ParameterLists.

        :param opimizer_list: The opimizer_list of this ParameterLists.
        :type opimizer_list: List[str]
        """

        self._opimizer_list = opimizer_list

    @property
    def momentum_list(self) -> List[float]:
        """
        Gets the momentum_list of this ParameterLists.

        :return: The momentum_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._momentum_list

    @momentum_list.setter
    def momentum_list(self, momentum_list: List[float]):
        """
        Sets the momentum_list of this ParameterLists.

        :param momentum_list: The momentum_list of this ParameterLists.
        :type momentum_list: List[float]
        """

        self._momentum_list = momentum_list

    @property
    def random_function_for_weights_list(self) -> List[str]:
        """
        Gets the random_function_for_weights_list of this ParameterLists.

        :return: The random_function_for_weights_list of this ParameterLists.
        :rtype: List[str]
        """
        return self._random_function_for_weights_list

    @random_function_for_weights_list.setter
    def random_function_for_weights_list(self, random_function_for_weights_list: List[str]):
        """
        Sets the random_function_for_weights_list of this ParameterLists.

        :param random_function_for_weights_list: The random_function_for_weights_list of this ParameterLists.
        :type random_function_for_weights_list: List[str]
        """

        self._random_function_for_weights_list = random_function_for_weights_list

    @property
    def rw_alpha_list(self) -> List[float]:
        """
        Gets the rw_alpha_list of this ParameterLists.

        :return: The rw_alpha_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_alpha_list

    @rw_alpha_list.setter
    def rw_alpha_list(self, rw_alpha_list: List[float]):
        """
        Sets the rw_alpha_list of this ParameterLists.

        :param rw_alpha_list: The rw_alpha_list of this ParameterLists.
        :type rw_alpha_list: List[float]
        """

        self._rw_alpha_list = rw_alpha_list

    @property
    def rw_beta_list(self) -> List[float]:
        """
        Gets the rw_beta_list of this ParameterLists.

        :return: The rw_beta_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_beta_list

    @rw_beta_list.setter
    def rw_beta_list(self, rw_beta_list: List[float]):
        """
        Sets the rw_beta_list of this ParameterLists.

        :param rw_beta_list: The rw_beta_list of this ParameterLists.
        :type rw_beta_list: List[float]
        """

        self._rw_beta_list = rw_beta_list

    @property
    def rw_mean_list(self) -> List[float]:
        """
        Gets the rw_mean_list of this ParameterLists.

        :return: The rw_mean_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_mean_list

    @rw_mean_list.setter
    def rw_mean_list(self, rw_mean_list: List[float]):
        """
        Sets the rw_mean_list of this ParameterLists.

        :param rw_mean_list: The rw_mean_list of this ParameterLists.
        :type rw_mean_list: List[float]
        """

        self._rw_mean_list = rw_mean_list

    @property
    def rw_stddev_list(self) -> List[float]:
        """
        Gets the rw_stddev_list of this ParameterLists.

        :return: The rw_stddev_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_stddev_list

    @rw_stddev_list.setter
    def rw_stddev_list(self, rw_stddev_list: List[float]):
        """
        Sets the rw_stddev_list of this ParameterLists.

        :param rw_stddev_list: The rw_stddev_list of this ParameterLists.
        :type rw_stddev_list: List[float]
        """

        self._rw_stddev_list = rw_stddev_list

    @property
    def rw_lam_list(self) -> List[float]:
        """
        Gets the rw_lam_list of this ParameterLists.

        :return: The rw_lam_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_lam_list

    @rw_lam_list.setter
    def rw_lam_list(self, rw_lam_list: List[float]):
        """
        Sets the rw_lam_list of this ParameterLists.

        :param rw_lam_list: The rw_lam_list of this ParameterLists.
        :type rw_lam_list: List[float]
        """

        self._rw_lam_list = rw_lam_list

    @property
    def rw_minval_list(self) -> List[float]:
        """
        Gets the rw_minval_list of this ParameterLists.

        :return: The rw_minval_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_minval_list

    @rw_minval_list.setter
    def rw_minval_list(self, rw_minval_list: List[float]):
        """
        Sets the rw_minval_list of this ParameterLists.

        :param rw_minval_list: The rw_minval_list of this ParameterLists.
        :type rw_minval_list: List[float]
        """

        self._rw_minval_list = rw_minval_list

    @property
    def rw_maxval_list(self) -> List[float]:
        """
        Gets the rw_maxval_list of this ParameterLists.

        :return: The rw_maxval_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rw_maxval_list

    @rw_maxval_list.setter
    def rw_maxval_list(self, rw_maxval_list: List[float]):
        """
        Sets the rw_maxval_list of this ParameterLists.

        :param rw_maxval_list: The rw_maxval_list of this ParameterLists.
        :type rw_maxval_list: List[float]
        """

        self._rw_maxval_list = rw_maxval_list

    @property
    def rw_seed_list(self) -> List[int]:
        """
        Gets the rw_seed_list of this ParameterLists.

        :return: The rw_seed_list of this ParameterLists.
        :rtype: List[int]
        """
        return self._rw_seed_list

    @rw_seed_list.setter
    def rw_seed_list(self, rw_seed_list: List[int]):
        """
        Sets the rw_seed_list of this ParameterLists.

        :param rw_seed_list: The rw_seed_list of this ParameterLists.
        :type rw_seed_list: List[int]
        """

        self._rw_seed_list = rw_seed_list

    @property
    def random_function_for_biases_list(self) -> List[str]:
        """
        Gets the random_function_for_biases_list of this ParameterLists.

        :return: The random_function_for_biases_list of this ParameterLists.
        :rtype: List[str]
        """
        return self._random_function_for_biases_list

    @random_function_for_biases_list.setter
    def random_function_for_biases_list(self, random_function_for_biases_list: List[str]):
        """
        Sets the random_function_for_biases_list of this ParameterLists.

        :param random_function_for_biases_list: The random_function_for_biases_list of this ParameterLists.
        :type random_function_for_biases_list: List[str]
        """

        self._random_function_for_biases_list = random_function_for_biases_list

    @property
    def rb_alpha_list(self) -> List[float]:
        """
        Gets the rb_alpha_list of this ParameterLists.

        :return: The rb_alpha_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_alpha_list

    @rb_alpha_list.setter
    def rb_alpha_list(self, rb_alpha_list: List[float]):
        """
        Sets the rb_alpha_list of this ParameterLists.

        :param rb_alpha_list: The rb_alpha_list of this ParameterLists.
        :type rb_alpha_list: List[float]
        """

        self._rb_alpha_list = rb_alpha_list

    @property
    def rb_beta_list(self) -> List[float]:
        """
        Gets the rb_beta_list of this ParameterLists.

        :return: The rb_beta_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_beta_list

    @rb_beta_list.setter
    def rb_beta_list(self, rb_beta_list: List[float]):
        """
        Sets the rb_beta_list of this ParameterLists.

        :param rb_beta_list: The rb_beta_list of this ParameterLists.
        :type rb_beta_list: List[float]
        """

        self._rb_beta_list = rb_beta_list

    @property
    def rb_mean_list(self) -> List[float]:
        """
        Gets the rb_mean_list of this ParameterLists.

        :return: The rb_mean_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_mean_list

    @rb_mean_list.setter
    def rb_mean_list(self, rb_mean_list: List[float]):
        """
        Sets the rb_mean_list of this ParameterLists.

        :param rb_mean_list: The rb_mean_list of this ParameterLists.
        :type rb_mean_list: List[float]
        """

        self._rb_mean_list = rb_mean_list

    @property
    def rb_stddev_list(self) -> List[float]:
        """
        Gets the rb_stddev_list of this ParameterLists.

        :return: The rb_stddev_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_stddev_list

    @rb_stddev_list.setter
    def rb_stddev_list(self, rb_stddev_list: List[float]):
        """
        Sets the rb_stddev_list of this ParameterLists.

        :param rb_stddev_list: The rb_stddev_list of this ParameterLists.
        :type rb_stddev_list: List[float]
        """

        self._rb_stddev_list = rb_stddev_list

    @property
    def rb_lam_list(self) -> List[float]:
        """
        Gets the rb_lam_list of this ParameterLists.

        :return: The rb_lam_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_lam_list

    @rb_lam_list.setter
    def rb_lam_list(self, rb_lam_list: List[float]):
        """
        Sets the rb_lam_list of this ParameterLists.

        :param rb_lam_list: The rb_lam_list of this ParameterLists.
        :type rb_lam_list: List[float]
        """

        self._rb_lam_list = rb_lam_list

    @property
    def rb_minval_list(self) -> List[float]:
        """
        Gets the rb_minval_list of this ParameterLists.

        :return: The rb_minval_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_minval_list

    @rb_minval_list.setter
    def rb_minval_list(self, rb_minval_list: List[float]):
        """
        Sets the rb_minval_list of this ParameterLists.

        :param rb_minval_list: The rb_minval_list of this ParameterLists.
        :type rb_minval_list: List[float]
        """

        self._rb_minval_list = rb_minval_list

    @property
    def rb_maxval_list(self) -> List[float]:
        """
        Gets the rb_maxval_list of this ParameterLists.

        :return: The rb_maxval_list of this ParameterLists.
        :rtype: List[float]
        """
        return self._rb_maxval_list

    @rb_maxval_list.setter
    def rb_maxval_list(self, rb_maxval_list: List[float]):
        """
        Sets the rb_maxval_list of this ParameterLists.

        :param rb_maxval_list: The rb_maxval_list of this ParameterLists.
        :type rb_maxval_list: List[float]
        """

        self._rb_maxval_list = rb_maxval_list

    @property
    def rb_seed_list(self) -> List[int]:
        """
        Gets the rb_seed_list of this ParameterLists.

        :return: The rb_seed_list of this ParameterLists.
        :rtype: List[int]
        """
        return self._rb_seed_list

    @rb_seed_list.setter
    def rb_seed_list(self, rb_seed_list: List[int]):
        """
        Sets the rb_seed_list of this ParameterLists.

        :param rb_seed_list: The rb_seed_list of this ParameterLists.
        :type rb_seed_list: List[int]
        """

        self._rb_seed_list = rb_seed_list

    @property
    def session_saver_path(self) -> str:
        """
        Gets the session_saver_path of this ParameterLists.

        :return: The session_saver_path of this ParameterLists.
        :rtype: str
        """
        return self._session_saver_path

    @session_saver_path.setter
    def session_saver_path(self, session_saver_path: str):
        """
        Sets the session_saver_path of this ParameterLists.

        :param session_saver_path: The session_saver_path of this ParameterLists.
        :type session_saver_path: str
        """

        self._session_saver_path = session_saver_path

    @property
    def load_prev_session(self) -> bool:
        """
        Gets the load_prev_session of this ParameterLists.

        :return: The load_prev_session of this ParameterLists.
        :rtype: bool
        """
        return self._load_prev_session

    @load_prev_session.setter
    def load_prev_session(self, load_prev_session: bool):
        """
        Sets the load_prev_session of this ParameterLists.

        :param load_prev_session: The load_prev_session of this ParameterLists.
        :type load_prev_session: bool
        """

        self._load_prev_session = load_prev_session

