/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.TuneApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * WebUI to build, train and tune a Convolutional Autoencoder
 * Version: 1.0.5
 * Generated by: io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
 */
/**
 * @license Apache 2.0
 * http://www.apache.org/licenses/LICENSE-2.0.html
 */

goog.provide('API.Client.TuneApi');

goog.require('API.Client.ParameterList');
goog.require('API.Client.ProcessedImageData');
goog.require('API.Client.TrainPerformance');
goog.require('API.Client.TrainStatus');

/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.TuneApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('TuneApiBasePath') ?
                   /** @type {!string} */ ($injector.get('TuneApiBasePath')) :
                   'http://localhost:8080/v2';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('TuneApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('TuneApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.TuneApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * starts, pauses and stops the tuning
 * 
 * @param {!TrainStatus} trainStatus new status for training
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.TuneApi.prototype.controlTuning = function(trainStatus, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/tune/controlTuning';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'trainStatus' is set
  if (!trainStatus) {
    throw new Error('Missing required parameter trainStatus when calling controlTuning');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'PUT',
    url: path,
    json: true,
    data: trainStatus,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * returns a subset of the current train images and the corresponding latent representation and output
 * 
 * @param {!number} setSize size of the image subset
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.ProcessedImageData>}
 */
API.Client.TuneApi.prototype.getProcessedImageDataOfCurrentTuning = function(setSize, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/tune/getProcessedImageDataOfCurrentTuning';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'setSize' is set
  if (!setSize) {
    throw new Error('Missing required parameter setSize when calling getProcessedImageDataOfCurrentTuning');
  }
  if (setSize !== undefined) {
    queryParameters['setSize'] = setSize;
  }

  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * returns the next batch of scalar train variables
 * as list of dicts
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.TrainPerformance>}
 */
API.Client.TuneApi.prototype.getTrainPerformanceOfCurrentTuning = function(opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/tune/getTrainPerformanceOfCurrentTuning';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * passes all learning and ANN parameters to the server
 * Includes learning parameters and ANN topology as lists
 * @param {!ParameterList} inputParameterLists object with all tunable parameter lists
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.TuneApi.prototype.passANNParameterLists = function(inputParameterLists, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/tune/buildGridSearchANN';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'inputParameterLists' is set
  if (!inputParameterLists) {
    throw new Error('Missing required parameter inputParameterLists when calling passANNParameterLists');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'POST',
    url: path,
    json: true,
    data: inputParameterLists,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
