# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ParameterList(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, input_shape: List[List[int]]=None, number_of_stacks: List[List[int]]=None, filter_sizes: List[List[int]]=None, mirror_weights: List[bool]=None, activation_function: List[str]=None, batch_size: List[int]=None, n_epochs: List[int]=None, use_tensorboard: bool=None, verbose: bool=None, learning_rate_function: List[str]=None, lr_initial_learning_rate: List[float]=None, lr_decay_steps: List[int]=None, lr_decay_rate: List[float]=None, lr_staircase: List[bool]=None, lr_boundaries: List[List[int]]=None, lr_values: List[List[float]]=None, lr_end_learning_rate: List[float]=None, lr_power: List[float]=None, lr_cycle: List[bool]=None, optimizer: List[str]=None, momentum: List[float]=None, random_function_for_weights: List[str]=None, rw_alpha: List[float]=None, rw_beta: List[float]=None, rw_mean: List[float]=None, rw_stddev: List[float]=None, rw_lam: List[float]=None, rw_minval: List[float]=None, rw_maxval: List[float]=None, rw_seed: List[int]=None, random_function_for_biases: List[str]=None, rb_alpha: List[float]=None, rb_beta: List[float]=None, rb_mean: List[float]=None, rb_stddev: List[float]=None, rb_lam: List[float]=None, rb_minval: List[float]=None, rb_maxval: List[float]=None, rb_seed: List[int]=None, session_saver_path: str=None, load_prev_session: bool=None, session_save_duration: List[int]=None, num_test_pictures: List[int]=None):
        """
        ParameterList - a model defined in Swagger

        :param input_shape: The input_shape of this ParameterList.
        :type input_shape: List[List[int]]
        :param number_of_stacks: The number_of_stacks of this ParameterList.
        :type number_of_stacks: List[List[int]]
        :param filter_sizes: The filter_sizes of this ParameterList.
        :type filter_sizes: List[List[int]]
        :param mirror_weights: The mirror_weights of this ParameterList.
        :type mirror_weights: List[bool]
        :param activation_function: The activation_function of this ParameterList.
        :type activation_function: List[str]
        :param batch_size: The batch_size of this ParameterList.
        :type batch_size: List[int]
        :param n_epochs: The n_epochs of this ParameterList.
        :type n_epochs: List[int]
        :param use_tensorboard: The use_tensorboard of this ParameterList.
        :type use_tensorboard: bool
        :param verbose: The verbose of this ParameterList.
        :type verbose: bool
        :param learning_rate_function: The learning_rate_function of this ParameterList.
        :type learning_rate_function: List[str]
        :param lr_initial_learning_rate: The lr_initial_learning_rate of this ParameterList.
        :type lr_initial_learning_rate: List[float]
        :param lr_decay_steps: The lr_decay_steps of this ParameterList.
        :type lr_decay_steps: List[int]
        :param lr_decay_rate: The lr_decay_rate of this ParameterList.
        :type lr_decay_rate: List[float]
        :param lr_staircase: The lr_staircase of this ParameterList.
        :type lr_staircase: List[bool]
        :param lr_boundaries: The lr_boundaries of this ParameterList.
        :type lr_boundaries: List[List[int]]
        :param lr_values: The lr_values of this ParameterList.
        :type lr_values: List[List[float]]
        :param lr_end_learning_rate: The lr_end_learning_rate of this ParameterList.
        :type lr_end_learning_rate: List[float]
        :param lr_power: The lr_power of this ParameterList.
        :type lr_power: List[float]
        :param lr_cycle: The lr_cycle of this ParameterList.
        :type lr_cycle: List[bool]
        :param optimizer: The optimizer of this ParameterList.
        :type optimizer: List[str]
        :param momentum: The momentum of this ParameterList.
        :type momentum: List[float]
        :param random_function_for_weights: The random_function_for_weights of this ParameterList.
        :type random_function_for_weights: List[str]
        :param rw_alpha: The rw_alpha of this ParameterList.
        :type rw_alpha: List[float]
        :param rw_beta: The rw_beta of this ParameterList.
        :type rw_beta: List[float]
        :param rw_mean: The rw_mean of this ParameterList.
        :type rw_mean: List[float]
        :param rw_stddev: The rw_stddev of this ParameterList.
        :type rw_stddev: List[float]
        :param rw_lam: The rw_lam of this ParameterList.
        :type rw_lam: List[float]
        :param rw_minval: The rw_minval of this ParameterList.
        :type rw_minval: List[float]
        :param rw_maxval: The rw_maxval of this ParameterList.
        :type rw_maxval: List[float]
        :param rw_seed: The rw_seed of this ParameterList.
        :type rw_seed: List[int]
        :param random_function_for_biases: The random_function_for_biases of this ParameterList.
        :type random_function_for_biases: List[str]
        :param rb_alpha: The rb_alpha of this ParameterList.
        :type rb_alpha: List[float]
        :param rb_beta: The rb_beta of this ParameterList.
        :type rb_beta: List[float]
        :param rb_mean: The rb_mean of this ParameterList.
        :type rb_mean: List[float]
        :param rb_stddev: The rb_stddev of this ParameterList.
        :type rb_stddev: List[float]
        :param rb_lam: The rb_lam of this ParameterList.
        :type rb_lam: List[float]
        :param rb_minval: The rb_minval of this ParameterList.
        :type rb_minval: List[float]
        :param rb_maxval: The rb_maxval of this ParameterList.
        :type rb_maxval: List[float]
        :param rb_seed: The rb_seed of this ParameterList.
        :type rb_seed: List[int]
        :param session_saver_path: The session_saver_path of this ParameterList.
        :type session_saver_path: str
        :param load_prev_session: The load_prev_session of this ParameterList.
        :type load_prev_session: bool
        :param session_save_duration: The session_save_duration of this ParameterList.
        :type session_save_duration: List[int]
        :param num_test_pictures: The num_test_pictures of this ParameterList.
        :type num_test_pictures: List[int]
        """
        self.swagger_types = {
            'input_shape': List[List[int]],
            'number_of_stacks': List[List[int]],
            'filter_sizes': List[List[int]],
            'mirror_weights': List[bool],
            'activation_function': List[str],
            'batch_size': List[int],
            'n_epochs': List[int],
            'use_tensorboard': bool,
            'verbose': bool,
            'learning_rate_function': List[str],
            'lr_initial_learning_rate': List[float],
            'lr_decay_steps': List[int],
            'lr_decay_rate': List[float],
            'lr_staircase': List[bool],
            'lr_boundaries': List[List[int]],
            'lr_values': List[List[float]],
            'lr_end_learning_rate': List[float],
            'lr_power': List[float],
            'lr_cycle': List[bool],
            'optimizer': List[str],
            'momentum': List[float],
            'random_function_for_weights': List[str],
            'rw_alpha': List[float],
            'rw_beta': List[float],
            'rw_mean': List[float],
            'rw_stddev': List[float],
            'rw_lam': List[float],
            'rw_minval': List[float],
            'rw_maxval': List[float],
            'rw_seed': List[int],
            'random_function_for_biases': List[str],
            'rb_alpha': List[float],
            'rb_beta': List[float],
            'rb_mean': List[float],
            'rb_stddev': List[float],
            'rb_lam': List[float],
            'rb_minval': List[float],
            'rb_maxval': List[float],
            'rb_seed': List[int],
            'session_saver_path': str,
            'load_prev_session': bool,
            'session_save_duration': List[int],
            'num_test_pictures': List[int]
        }

        self.attribute_map = {
            'input_shape': 'input_shape',
            'number_of_stacks': 'number_of_stacks',
            'filter_sizes': 'filter_sizes',
            'mirror_weights': 'mirror_weights',
            'activation_function': 'activation_function',
            'batch_size': 'batch_size',
            'n_epochs': 'n_epochs',
            'use_tensorboard': 'use_tensorboard',
            'verbose': 'verbose',
            'learning_rate_function': 'learning_rate_function',
            'lr_initial_learning_rate': 'lr_initial_learning_rate',
            'lr_decay_steps': 'lr_decay_steps',
            'lr_decay_rate': 'lr_decay_rate',
            'lr_staircase': 'lr_staircase',
            'lr_boundaries': 'lr_boundaries',
            'lr_values': 'lr_values',
            'lr_end_learning_rate': 'lr_end_learning_rate',
            'lr_power': 'lr_power',
            'lr_cycle': 'lr_cycle',
            'optimizer': 'optimizer',
            'momentum': 'momentum',
            'random_function_for_weights': 'random_function_for_weights',
            'rw_alpha': 'rw_alpha',
            'rw_beta': 'rw_beta',
            'rw_mean': 'rw_mean',
            'rw_stddev': 'rw_stddev',
            'rw_lam': 'rw_lam',
            'rw_minval': 'rw_minval',
            'rw_maxval': 'rw_maxval',
            'rw_seed': 'rw_seed',
            'random_function_for_biases': 'random_function_for_biases',
            'rb_alpha': 'rb_alpha',
            'rb_beta': 'rb_beta',
            'rb_mean': 'rb_mean',
            'rb_stddev': 'rb_stddev',
            'rb_lam': 'rb_lam',
            'rb_minval': 'rb_minval',
            'rb_maxval': 'rb_maxval',
            'rb_seed': 'rb_seed',
            'session_saver_path': 'session_saver_path',
            'load_prev_session': 'load_prev_session',
            'session_save_duration': 'session_save_duration',
            'num_test_pictures': 'num_test_pictures'
        }

        self._input_shape = input_shape
        self._number_of_stacks = number_of_stacks
        self._filter_sizes = filter_sizes
        self._mirror_weights = mirror_weights
        self._activation_function = activation_function
        self._batch_size = batch_size
        self._n_epochs = n_epochs
        self._use_tensorboard = use_tensorboard
        self._verbose = verbose
        self._learning_rate_function = learning_rate_function
        self._lr_initial_learning_rate = lr_initial_learning_rate
        self._lr_decay_steps = lr_decay_steps
        self._lr_decay_rate = lr_decay_rate
        self._lr_staircase = lr_staircase
        self._lr_boundaries = lr_boundaries
        self._lr_values = lr_values
        self._lr_end_learning_rate = lr_end_learning_rate
        self._lr_power = lr_power
        self._lr_cycle = lr_cycle
        self._optimizer = optimizer
        self._momentum = momentum
        self._random_function_for_weights = random_function_for_weights
        self._rw_alpha = rw_alpha
        self._rw_beta = rw_beta
        self._rw_mean = rw_mean
        self._rw_stddev = rw_stddev
        self._rw_lam = rw_lam
        self._rw_minval = rw_minval
        self._rw_maxval = rw_maxval
        self._rw_seed = rw_seed
        self._random_function_for_biases = random_function_for_biases
        self._rb_alpha = rb_alpha
        self._rb_beta = rb_beta
        self._rb_mean = rb_mean
        self._rb_stddev = rb_stddev
        self._rb_lam = rb_lam
        self._rb_minval = rb_minval
        self._rb_maxval = rb_maxval
        self._rb_seed = rb_seed
        self._session_saver_path = session_saver_path
        self._load_prev_session = load_prev_session
        self._session_save_duration = session_save_duration
        self._num_test_pictures = num_test_pictures

    @classmethod
    def from_dict(cls, dikt) -> 'ParameterList':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParameterList of this ParameterList.
        :rtype: ParameterList
        """
        return deserialize_model(dikt, cls)

    @property
    def input_shape(self) -> List[List[int]]:
        """
        Gets the input_shape of this ParameterList.

        :return: The input_shape of this ParameterList.
        :rtype: List[List[int]]
        """
        return self._input_shape

    @input_shape.setter
    def input_shape(self, input_shape: List[List[int]]):
        """
        Sets the input_shape of this ParameterList.

        :param input_shape: The input_shape of this ParameterList.
        :type input_shape: List[List[int]]
        """

        self._input_shape = input_shape

    @property
    def number_of_stacks(self) -> List[List[int]]:
        """
        Gets the number_of_stacks of this ParameterList.

        :return: The number_of_stacks of this ParameterList.
        :rtype: List[List[int]]
        """
        return self._number_of_stacks

    @number_of_stacks.setter
    def number_of_stacks(self, number_of_stacks: List[List[int]]):
        """
        Sets the number_of_stacks of this ParameterList.

        :param number_of_stacks: The number_of_stacks of this ParameterList.
        :type number_of_stacks: List[List[int]]
        """

        self._number_of_stacks = number_of_stacks

    @property
    def filter_sizes(self) -> List[List[int]]:
        """
        Gets the filter_sizes of this ParameterList.

        :return: The filter_sizes of this ParameterList.
        :rtype: List[List[int]]
        """
        return self._filter_sizes

    @filter_sizes.setter
    def filter_sizes(self, filter_sizes: List[List[int]]):
        """
        Sets the filter_sizes of this ParameterList.

        :param filter_sizes: The filter_sizes of this ParameterList.
        :type filter_sizes: List[List[int]]
        """

        self._filter_sizes = filter_sizes

    @property
    def mirror_weights(self) -> List[bool]:
        """
        Gets the mirror_weights of this ParameterList.

        :return: The mirror_weights of this ParameterList.
        :rtype: List[bool]
        """
        return self._mirror_weights

    @mirror_weights.setter
    def mirror_weights(self, mirror_weights: List[bool]):
        """
        Sets the mirror_weights of this ParameterList.

        :param mirror_weights: The mirror_weights of this ParameterList.
        :type mirror_weights: List[bool]
        """

        self._mirror_weights = mirror_weights

    @property
    def activation_function(self) -> List[str]:
        """
        Gets the activation_function of this ParameterList.

        :return: The activation_function of this ParameterList.
        :rtype: List[str]
        """
        return self._activation_function

    @activation_function.setter
    def activation_function(self, activation_function: List[str]):
        """
        Sets the activation_function of this ParameterList.

        :param activation_function: The activation_function of this ParameterList.
        :type activation_function: List[str]
        """

        self._activation_function = activation_function

    @property
    def batch_size(self) -> List[int]:
        """
        Gets the batch_size of this ParameterList.

        :return: The batch_size of this ParameterList.
        :rtype: List[int]
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size: List[int]):
        """
        Sets the batch_size of this ParameterList.

        :param batch_size: The batch_size of this ParameterList.
        :type batch_size: List[int]
        """

        self._batch_size = batch_size

    @property
    def n_epochs(self) -> List[int]:
        """
        Gets the n_epochs of this ParameterList.

        :return: The n_epochs of this ParameterList.
        :rtype: List[int]
        """
        return self._n_epochs

    @n_epochs.setter
    def n_epochs(self, n_epochs: List[int]):
        """
        Sets the n_epochs of this ParameterList.

        :param n_epochs: The n_epochs of this ParameterList.
        :type n_epochs: List[int]
        """

        self._n_epochs = n_epochs

    @property
    def use_tensorboard(self) -> bool:
        """
        Gets the use_tensorboard of this ParameterList.

        :return: The use_tensorboard of this ParameterList.
        :rtype: bool
        """
        return self._use_tensorboard

    @use_tensorboard.setter
    def use_tensorboard(self, use_tensorboard: bool):
        """
        Sets the use_tensorboard of this ParameterList.

        :param use_tensorboard: The use_tensorboard of this ParameterList.
        :type use_tensorboard: bool
        """

        self._use_tensorboard = use_tensorboard

    @property
    def verbose(self) -> bool:
        """
        Gets the verbose of this ParameterList.

        :return: The verbose of this ParameterList.
        :rtype: bool
        """
        return self._verbose

    @verbose.setter
    def verbose(self, verbose: bool):
        """
        Sets the verbose of this ParameterList.

        :param verbose: The verbose of this ParameterList.
        :type verbose: bool
        """

        self._verbose = verbose

    @property
    def learning_rate_function(self) -> List[str]:
        """
        Gets the learning_rate_function of this ParameterList.

        :return: The learning_rate_function of this ParameterList.
        :rtype: List[str]
        """
        return self._learning_rate_function

    @learning_rate_function.setter
    def learning_rate_function(self, learning_rate_function: List[str]):
        """
        Sets the learning_rate_function of this ParameterList.

        :param learning_rate_function: The learning_rate_function of this ParameterList.
        :type learning_rate_function: List[str]
        """

        self._learning_rate_function = learning_rate_function

    @property
    def lr_initial_learning_rate(self) -> List[float]:
        """
        Gets the lr_initial_learning_rate of this ParameterList.

        :return: The lr_initial_learning_rate of this ParameterList.
        :rtype: List[float]
        """
        return self._lr_initial_learning_rate

    @lr_initial_learning_rate.setter
    def lr_initial_learning_rate(self, lr_initial_learning_rate: List[float]):
        """
        Sets the lr_initial_learning_rate of this ParameterList.

        :param lr_initial_learning_rate: The lr_initial_learning_rate of this ParameterList.
        :type lr_initial_learning_rate: List[float]
        """

        self._lr_initial_learning_rate = lr_initial_learning_rate

    @property
    def lr_decay_steps(self) -> List[int]:
        """
        Gets the lr_decay_steps of this ParameterList.

        :return: The lr_decay_steps of this ParameterList.
        :rtype: List[int]
        """
        return self._lr_decay_steps

    @lr_decay_steps.setter
    def lr_decay_steps(self, lr_decay_steps: List[int]):
        """
        Sets the lr_decay_steps of this ParameterList.

        :param lr_decay_steps: The lr_decay_steps of this ParameterList.
        :type lr_decay_steps: List[int]
        """

        self._lr_decay_steps = lr_decay_steps

    @property
    def lr_decay_rate(self) -> List[float]:
        """
        Gets the lr_decay_rate of this ParameterList.

        :return: The lr_decay_rate of this ParameterList.
        :rtype: List[float]
        """
        return self._lr_decay_rate

    @lr_decay_rate.setter
    def lr_decay_rate(self, lr_decay_rate: List[float]):
        """
        Sets the lr_decay_rate of this ParameterList.

        :param lr_decay_rate: The lr_decay_rate of this ParameterList.
        :type lr_decay_rate: List[float]
        """

        self._lr_decay_rate = lr_decay_rate

    @property
    def lr_staircase(self) -> List[bool]:
        """
        Gets the lr_staircase of this ParameterList.

        :return: The lr_staircase of this ParameterList.
        :rtype: List[bool]
        """
        return self._lr_staircase

    @lr_staircase.setter
    def lr_staircase(self, lr_staircase: List[bool]):
        """
        Sets the lr_staircase of this ParameterList.

        :param lr_staircase: The lr_staircase of this ParameterList.
        :type lr_staircase: List[bool]
        """

        self._lr_staircase = lr_staircase

    @property
    def lr_boundaries(self) -> List[List[int]]:
        """
        Gets the lr_boundaries of this ParameterList.

        :return: The lr_boundaries of this ParameterList.
        :rtype: List[List[int]]
        """
        return self._lr_boundaries

    @lr_boundaries.setter
    def lr_boundaries(self, lr_boundaries: List[List[int]]):
        """
        Sets the lr_boundaries of this ParameterList.

        :param lr_boundaries: The lr_boundaries of this ParameterList.
        :type lr_boundaries: List[List[int]]
        """

        self._lr_boundaries = lr_boundaries

    @property
    def lr_values(self) -> List[List[float]]:
        """
        Gets the lr_values of this ParameterList.

        :return: The lr_values of this ParameterList.
        :rtype: List[List[float]]
        """
        return self._lr_values

    @lr_values.setter
    def lr_values(self, lr_values: List[List[float]]):
        """
        Sets the lr_values of this ParameterList.

        :param lr_values: The lr_values of this ParameterList.
        :type lr_values: List[List[float]]
        """

        self._lr_values = lr_values

    @property
    def lr_end_learning_rate(self) -> List[float]:
        """
        Gets the lr_end_learning_rate of this ParameterList.

        :return: The lr_end_learning_rate of this ParameterList.
        :rtype: List[float]
        """
        return self._lr_end_learning_rate

    @lr_end_learning_rate.setter
    def lr_end_learning_rate(self, lr_end_learning_rate: List[float]):
        """
        Sets the lr_end_learning_rate of this ParameterList.

        :param lr_end_learning_rate: The lr_end_learning_rate of this ParameterList.
        :type lr_end_learning_rate: List[float]
        """

        self._lr_end_learning_rate = lr_end_learning_rate

    @property
    def lr_power(self) -> List[float]:
        """
        Gets the lr_power of this ParameterList.

        :return: The lr_power of this ParameterList.
        :rtype: List[float]
        """
        return self._lr_power

    @lr_power.setter
    def lr_power(self, lr_power: List[float]):
        """
        Sets the lr_power of this ParameterList.

        :param lr_power: The lr_power of this ParameterList.
        :type lr_power: List[float]
        """

        self._lr_power = lr_power

    @property
    def lr_cycle(self) -> List[bool]:
        """
        Gets the lr_cycle of this ParameterList.

        :return: The lr_cycle of this ParameterList.
        :rtype: List[bool]
        """
        return self._lr_cycle

    @lr_cycle.setter
    def lr_cycle(self, lr_cycle: List[bool]):
        """
        Sets the lr_cycle of this ParameterList.

        :param lr_cycle: The lr_cycle of this ParameterList.
        :type lr_cycle: List[bool]
        """

        self._lr_cycle = lr_cycle

    @property
    def optimizer(self) -> List[str]:
        """
        Gets the optimizer of this ParameterList.

        :return: The optimizer of this ParameterList.
        :rtype: List[str]
        """
        return self._optimizer

    @optimizer.setter
    def optimizer(self, optimizer: List[str]):
        """
        Sets the optimizer of this ParameterList.

        :param optimizer: The optimizer of this ParameterList.
        :type optimizer: List[str]
        """

        self._optimizer = optimizer

    @property
    def momentum(self) -> List[float]:
        """
        Gets the momentum of this ParameterList.

        :return: The momentum of this ParameterList.
        :rtype: List[float]
        """
        return self._momentum

    @momentum.setter
    def momentum(self, momentum: List[float]):
        """
        Sets the momentum of this ParameterList.

        :param momentum: The momentum of this ParameterList.
        :type momentum: List[float]
        """

        self._momentum = momentum

    @property
    def random_function_for_weights(self) -> List[str]:
        """
        Gets the random_function_for_weights of this ParameterList.

        :return: The random_function_for_weights of this ParameterList.
        :rtype: List[str]
        """
        return self._random_function_for_weights

    @random_function_for_weights.setter
    def random_function_for_weights(self, random_function_for_weights: List[str]):
        """
        Sets the random_function_for_weights of this ParameterList.

        :param random_function_for_weights: The random_function_for_weights of this ParameterList.
        :type random_function_for_weights: List[str]
        """

        self._random_function_for_weights = random_function_for_weights

    @property
    def rw_alpha(self) -> List[float]:
        """
        Gets the rw_alpha of this ParameterList.

        :return: The rw_alpha of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_alpha

    @rw_alpha.setter
    def rw_alpha(self, rw_alpha: List[float]):
        """
        Sets the rw_alpha of this ParameterList.

        :param rw_alpha: The rw_alpha of this ParameterList.
        :type rw_alpha: List[float]
        """

        self._rw_alpha = rw_alpha

    @property
    def rw_beta(self) -> List[float]:
        """
        Gets the rw_beta of this ParameterList.

        :return: The rw_beta of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_beta

    @rw_beta.setter
    def rw_beta(self, rw_beta: List[float]):
        """
        Sets the rw_beta of this ParameterList.

        :param rw_beta: The rw_beta of this ParameterList.
        :type rw_beta: List[float]
        """

        self._rw_beta = rw_beta

    @property
    def rw_mean(self) -> List[float]:
        """
        Gets the rw_mean of this ParameterList.

        :return: The rw_mean of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_mean

    @rw_mean.setter
    def rw_mean(self, rw_mean: List[float]):
        """
        Sets the rw_mean of this ParameterList.

        :param rw_mean: The rw_mean of this ParameterList.
        :type rw_mean: List[float]
        """

        self._rw_mean = rw_mean

    @property
    def rw_stddev(self) -> List[float]:
        """
        Gets the rw_stddev of this ParameterList.

        :return: The rw_stddev of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_stddev

    @rw_stddev.setter
    def rw_stddev(self, rw_stddev: List[float]):
        """
        Sets the rw_stddev of this ParameterList.

        :param rw_stddev: The rw_stddev of this ParameterList.
        :type rw_stddev: List[float]
        """

        self._rw_stddev = rw_stddev

    @property
    def rw_lam(self) -> List[float]:
        """
        Gets the rw_lam of this ParameterList.

        :return: The rw_lam of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_lam

    @rw_lam.setter
    def rw_lam(self, rw_lam: List[float]):
        """
        Sets the rw_lam of this ParameterList.

        :param rw_lam: The rw_lam of this ParameterList.
        :type rw_lam: List[float]
        """

        self._rw_lam = rw_lam

    @property
    def rw_minval(self) -> List[float]:
        """
        Gets the rw_minval of this ParameterList.

        :return: The rw_minval of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_minval

    @rw_minval.setter
    def rw_minval(self, rw_minval: List[float]):
        """
        Sets the rw_minval of this ParameterList.

        :param rw_minval: The rw_minval of this ParameterList.
        :type rw_minval: List[float]
        """

        self._rw_minval = rw_minval

    @property
    def rw_maxval(self) -> List[float]:
        """
        Gets the rw_maxval of this ParameterList.

        :return: The rw_maxval of this ParameterList.
        :rtype: List[float]
        """
        return self._rw_maxval

    @rw_maxval.setter
    def rw_maxval(self, rw_maxval: List[float]):
        """
        Sets the rw_maxval of this ParameterList.

        :param rw_maxval: The rw_maxval of this ParameterList.
        :type rw_maxval: List[float]
        """

        self._rw_maxval = rw_maxval

    @property
    def rw_seed(self) -> List[int]:
        """
        Gets the rw_seed of this ParameterList.

        :return: The rw_seed of this ParameterList.
        :rtype: List[int]
        """
        return self._rw_seed

    @rw_seed.setter
    def rw_seed(self, rw_seed: List[int]):
        """
        Sets the rw_seed of this ParameterList.

        :param rw_seed: The rw_seed of this ParameterList.
        :type rw_seed: List[int]
        """

        self._rw_seed = rw_seed

    @property
    def random_function_for_biases(self) -> List[str]:
        """
        Gets the random_function_for_biases of this ParameterList.

        :return: The random_function_for_biases of this ParameterList.
        :rtype: List[str]
        """
        return self._random_function_for_biases

    @random_function_for_biases.setter
    def random_function_for_biases(self, random_function_for_biases: List[str]):
        """
        Sets the random_function_for_biases of this ParameterList.

        :param random_function_for_biases: The random_function_for_biases of this ParameterList.
        :type random_function_for_biases: List[str]
        """

        self._random_function_for_biases = random_function_for_biases

    @property
    def rb_alpha(self) -> List[float]:
        """
        Gets the rb_alpha of this ParameterList.

        :return: The rb_alpha of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_alpha

    @rb_alpha.setter
    def rb_alpha(self, rb_alpha: List[float]):
        """
        Sets the rb_alpha of this ParameterList.

        :param rb_alpha: The rb_alpha of this ParameterList.
        :type rb_alpha: List[float]
        """

        self._rb_alpha = rb_alpha

    @property
    def rb_beta(self) -> List[float]:
        """
        Gets the rb_beta of this ParameterList.

        :return: The rb_beta of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_beta

    @rb_beta.setter
    def rb_beta(self, rb_beta: List[float]):
        """
        Sets the rb_beta of this ParameterList.

        :param rb_beta: The rb_beta of this ParameterList.
        :type rb_beta: List[float]
        """

        self._rb_beta = rb_beta

    @property
    def rb_mean(self) -> List[float]:
        """
        Gets the rb_mean of this ParameterList.

        :return: The rb_mean of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_mean

    @rb_mean.setter
    def rb_mean(self, rb_mean: List[float]):
        """
        Sets the rb_mean of this ParameterList.

        :param rb_mean: The rb_mean of this ParameterList.
        :type rb_mean: List[float]
        """

        self._rb_mean = rb_mean

    @property
    def rb_stddev(self) -> List[float]:
        """
        Gets the rb_stddev of this ParameterList.

        :return: The rb_stddev of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_stddev

    @rb_stddev.setter
    def rb_stddev(self, rb_stddev: List[float]):
        """
        Sets the rb_stddev of this ParameterList.

        :param rb_stddev: The rb_stddev of this ParameterList.
        :type rb_stddev: List[float]
        """

        self._rb_stddev = rb_stddev

    @property
    def rb_lam(self) -> List[float]:
        """
        Gets the rb_lam of this ParameterList.

        :return: The rb_lam of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_lam

    @rb_lam.setter
    def rb_lam(self, rb_lam: List[float]):
        """
        Sets the rb_lam of this ParameterList.

        :param rb_lam: The rb_lam of this ParameterList.
        :type rb_lam: List[float]
        """

        self._rb_lam = rb_lam

    @property
    def rb_minval(self) -> List[float]:
        """
        Gets the rb_minval of this ParameterList.

        :return: The rb_minval of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_minval

    @rb_minval.setter
    def rb_minval(self, rb_minval: List[float]):
        """
        Sets the rb_minval of this ParameterList.

        :param rb_minval: The rb_minval of this ParameterList.
        :type rb_minval: List[float]
        """

        self._rb_minval = rb_minval

    @property
    def rb_maxval(self) -> List[float]:
        """
        Gets the rb_maxval of this ParameterList.

        :return: The rb_maxval of this ParameterList.
        :rtype: List[float]
        """
        return self._rb_maxval

    @rb_maxval.setter
    def rb_maxval(self, rb_maxval: List[float]):
        """
        Sets the rb_maxval of this ParameterList.

        :param rb_maxval: The rb_maxval of this ParameterList.
        :type rb_maxval: List[float]
        """

        self._rb_maxval = rb_maxval

    @property
    def rb_seed(self) -> List[int]:
        """
        Gets the rb_seed of this ParameterList.

        :return: The rb_seed of this ParameterList.
        :rtype: List[int]
        """
        return self._rb_seed

    @rb_seed.setter
    def rb_seed(self, rb_seed: List[int]):
        """
        Sets the rb_seed of this ParameterList.

        :param rb_seed: The rb_seed of this ParameterList.
        :type rb_seed: List[int]
        """

        self._rb_seed = rb_seed

    @property
    def session_saver_path(self) -> str:
        """
        Gets the session_saver_path of this ParameterList.

        :return: The session_saver_path of this ParameterList.
        :rtype: str
        """
        return self._session_saver_path

    @session_saver_path.setter
    def session_saver_path(self, session_saver_path: str):
        """
        Sets the session_saver_path of this ParameterList.

        :param session_saver_path: The session_saver_path of this ParameterList.
        :type session_saver_path: str
        """

        self._session_saver_path = session_saver_path

    @property
    def load_prev_session(self) -> bool:
        """
        Gets the load_prev_session of this ParameterList.

        :return: The load_prev_session of this ParameterList.
        :rtype: bool
        """
        return self._load_prev_session

    @load_prev_session.setter
    def load_prev_session(self, load_prev_session: bool):
        """
        Sets the load_prev_session of this ParameterList.

        :param load_prev_session: The load_prev_session of this ParameterList.
        :type load_prev_session: bool
        """

        self._load_prev_session = load_prev_session

    @property
    def session_save_duration(self) -> List[int]:
        """
        Gets the session_save_duration of this ParameterList.

        :return: The session_save_duration of this ParameterList.
        :rtype: List[int]
        """
        return self._session_save_duration

    @session_save_duration.setter
    def session_save_duration(self, session_save_duration: List[int]):
        """
        Sets the session_save_duration of this ParameterList.

        :param session_save_duration: The session_save_duration of this ParameterList.
        :type session_save_duration: List[int]
        """

        self._session_save_duration = session_save_duration

    @property
    def num_test_pictures(self) -> List[int]:
        """
        Gets the num_test_pictures of this ParameterList.

        :return: The num_test_pictures of this ParameterList.
        :rtype: List[int]
        """
        return self._num_test_pictures

    @num_test_pictures.setter
    def num_test_pictures(self, num_test_pictures: List[int]):
        """
        Sets the num_test_pictures of this ParameterList.

        :param num_test_pictures: The num_test_pictures of this ParameterList.
        :type num_test_pictures: List[int]
        """

        self._num_test_pictures = num_test_pictures

