# coding: utf-8

from __future__ import absolute_import

from flask_server.swagger_server.util import deserialize_model
from .base_model_ import Model


class TrainStatus(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        TrainStatus - a model defined in Swagger

        """
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }


    @classmethod
    def from_dict(cls, dikt) -> 'TrainStatus':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainStatus of this TrainStatus.
        :rtype: TrainStatus
        """
        return deserialize_model(dikt, cls)
