# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model


class TrainStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    START = "start"
    PAUSE = "pause"
    STOP = "stop"
    RESUME = "resume"

    def __init__(self):  # noqa: E501
        """TrainStatus - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TrainStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainStatus of this TrainStatus.  # noqa: E501
        :rtype: TrainStatus
        """
        return util.deserialize_model(dikt, cls)
